# Generated by Django 2.2.1 on 2019-07-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20190717_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingprofile',
            options={'verbose_name': 'Платежный профиль', 'verbose_name_plural': 'Платежные профили'},
        ),
    ]
