# Generated by Django 2.2.1 on 2019-06-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_catsubrus_old_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryzacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_category_href', models.TextField(null=True)),
                ('list_category_name', models.TextField(null=True)),
                ('name', models.CharField(max_length=500, null=True)),
                ('url', models.TextField(null=True)),
                ('rus_name', models.CharField(max_length=500, null=True)),
                ('parent_id', models.IntegerField()),
            ],
        ),
    ]
