# Generated by Django 2.2.1 on 2019-06-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_categoryzacia'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catsubrus',
            table='cat_sub',
        ),
    ]
