# Generated by Django 2.2.1 on 2019-06-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20190628_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catsubrus',
            old_name='old_id',
            new_name='c_id',
        ),
    ]
