# Generated by Django 2.2.1 on 2019-06-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20190629_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatestsmall',
            name='title_rus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
