# Generated by Django 2.2.1 on 2019-06-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20190629_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatestsmall',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
