# Generated by Django 2.2.1 on 2019-07-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20190703_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alegrogoods',
            name='delivery_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='alegrogoods',
            name='param',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='alegrogoods',
            name='subcat_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
