# Generated by Django 2.2.1 on 2019-07-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20190703_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alegrogoods',
            old_name='condition',
            new_name='cond',
        ),
    ]
