# Generated by Django 2.2.1 on 2019-07-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20190703_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alegrogoods',
            old_name='descriptino',
            new_name='description',
        ),
    ]
