# Generated by Django 2.2.1 on 2019-07-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20190703_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alegrogoods',
            name='allegro_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
