# Generated by Django 2.2.1 on 2019-07-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20190703_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alegrogoods',
            name='cat_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
