# Generated by Django 2.2.1 on 2019-07-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20190703_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alegrogoods',
            name='cat_id',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
