# Generated by Django 2.2.1 on 2019-07-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20190703_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alegrogoods',
            name='subsubcat_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
