# Generated by Django 2.2.1 on 2019-07-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20190703_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alegrogoods',
            old_name='trash1',
            new_name='fuel',
        ),
        migrations.RenameField(
            model_name='alegrogoods',
            old_name='trash2',
            new_name='value',
        ),
    ]
