# Generated by Django 2.2.1 on 2019-07-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20190704_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='alegrogoods',
            name='blank',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
