# Generated by Django 2.2.1 on 2019-07-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alegrogoods_blank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alegrogoods',
            name='blank',
        ),
        migrations.AddField(
            model_name='alegrogoods',
            name='slug',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
