# Generated by Django 2.2.1 on 2019-07-08 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_auto_20190705_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alegrogoods',
            name='cat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product.CatSubRus'),
        ),
        migrations.AlterField(
            model_name='alegrogoods',
            name='id_data',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
