# Generated by Django 2.2.1 on 2019-07-08 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_auto_20190708_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alegrogoods',
            name='cat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cat_id', to='product.CatSubRus'),
        ),
    ]
