# Generated by Django 2.2.1 on 2019-07-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_auto_20190708_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alegrogoods',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
