# Generated by Django 2.2.1 on 2019-07-12 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_auto_20190712_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catsubrus',
            name='super_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.SuperCat'),
        ),
    ]
