# Generated by Django 2.2.1 on 2019-07-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_auto_20190712_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercat',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Корневой Раздел'),
        ),
    ]
