# Generated by Django 2.2.1 on 2019-07-12 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_auto_20190712_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catsubrus',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.CatSubRus'),
        ),
    ]
