# Generated by Django 2.2.1 on 2019-07-12 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_auto_20190712_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('on_main', models.BooleanField(default=False)),
                ('product_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.AlegroGoods')),
            ],
            options={
                'verbose_name_plural': 'Товары на главной',
            },
        ),
        migrations.DeleteModel(
            name='Categoryzacia',
        ),
        migrations.DeleteModel(
            name='DataTest',
        ),
        migrations.AlterModelOptions(
            name='catsubrus',
            options={'verbose_name_plural': 'Категории Авто'},
        ),
        migrations.AlterModelOptions(
            name='supercat',
            options={'verbose_name_plural': 'Корневые категории'},
        ),
    ]
