# Generated by Django 2.2.1 on 2019-07-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_auto_20190712_0933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataTestSmall',
        ),
    ]
