# Generated by Django 2.2.1 on 2019-07-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_delete_datatestsmall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredproduct',
            name='title',
        ),
        migrations.AlterField(
            model_name='featuredproduct',
            name='on_main',
            field=models.IntegerField(choices=[(1, 'Главная легковые запчасти'), (2, 'Главная новые поступления'), (3, 'Запчасти к спецтехнике'), (4, 'Новые поступления'), (5, 'Разные запчасти'), (6, 'Фичуред продукт'), (7, 'Часто просматриваемые'), (8, 'Бестселлер')], default=1),
        ),
    ]
