# Generated by Django 2.2.1 on 2019-07-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_auto_20190712_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='on_main',
            field=models.IntegerField(choices=[(1, 'Легковые запчасти'), (2, 'Новые поступления'), (3, 'Запчасти к спецтехнике'), (5, 'Разные запчасти'), (6, 'Фичуред продукт'), (7, 'Часто просматриваемые'), (8, 'Бестселлер')], default=1),
        ),
    ]
