# Generated by Django 2.2.1 on 2019-08-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_auto_20190730_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alegrogoods',
            name='brand',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alegrogoods',
            name='car',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alegrogoods',
            name='cond',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alegrogoods',
            name='img',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
