# Generated by Django 2.2.1 on 2019-08-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_auto_20190805_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alegrogoods',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
