# Generated by Django 2.2.1 on 2019-08-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_auto_20190805_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alegrogoods',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
