# Generated by Django 2.2.1 on 2019-09-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_auto_20190807_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alegrogoods',
            name='subcat_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='alegrogoods',
            name='subsubcat_id',
            field=models.TextField(null=True),
        ),
    ]
