# Generated by Django 2.2.1 on 2019-06-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_author_blog_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
