# Generated by Django 2.2.1 on 2019-07-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190712_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategories',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
