# Generated by Django 2.2.1 on 2019-07-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190712_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='publish',
            field=models.DateField(auto_now=True),
        ),
    ]
