# Generated by Django 2.2.1 on 2019-07-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogmodel_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategories',
            options={'verbose_name_plural': 'Категории блога'},
        ),
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'verbose_name_plural': 'Статьи'},
        ),
    ]
