# Generated by Django 2.2.1 on 2019-08-05 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatSubRusSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('rus_name', models.CharField(max_length=255, null=True)),
                ('parent_id', models.IntegerField(null=True)),
                ('slug', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Категории Авто',
                'db_table': 'cat_sub_spec',
            },
        ),
        migrations.CreateModel(
            name='AlegroGoodsSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('allegro_id', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField(null=True)),
                ('price_pol', models.IntegerField(null=True)),
                ('delivery_price', models.FloatField(null=True)),
                ('img', models.CharField(max_length=1000)),
                ('cond', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('car', models.CharField(max_length=255)),
                ('car_model', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(max_length=255, null=True)),
                ('cat_n', models.CharField(max_length=255, null=True)),
                ('brand_n', models.CharField(max_length=255, null=True)),
                ('param', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField()),
                ('description_clean', models.TextField(null=True)),
                ('subcat_id', models.CharField(max_length=255, null=True)),
                ('subsubcat_id', models.CharField(max_length=100, null=True)),
                ('id_data', models.CharField(max_length=100, null=True)),
                ('color', models.CharField(max_length=255, null=True)),
                ('stan', models.CharField(max_length=255, null=True)),
                ('fuel', models.CharField(max_length=255, null=True)),
                ('value', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('slug', models.CharField(max_length=255, null=True, unique=True)),
                ('name_pol', models.CharField(blank=True, max_length=255, null=True)),
                ('cat_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cat_id', to='product_spec.CatSubRusSpec')),
            ],
            options={
                'db_table': 'product_allegro_spec',
                'managed': True,
            },
        ),
    ]
