# Generated by Django 2.2.1 on 2019-07-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190718_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_addres',
            new_name='shipping_address',
        ),
    ]
